### ISSUE TITLE
Make a Hamburger for mobile.

### ISSUE THREAD

**Issue by praveen-me** [praveen-me/praveen-me.github.io#1]

**Comment by praveen-me** [comment]
Ya. Hamburger, when it is pressed the navbar will expand.

**Comment by ksandhu16** [comment]
I will work on this.

**Comment by praveen-me** [comment]
Ya, But first I'm waiting for @omergulen response.

**Comment by praveen-me** [comment]
@ksandhu16 you can work on it.

**Comment by omergulen** [comment]
If you can give more specifications, I can change its style.

**Comment by praveen-me** [comment]
Please don't the color scheme and make styling or hovering please proper. @omergulen

**Comment by adsingh14** [comment]
@praveen-me Need any help ? 🙂
